image: maven:3.6.1-jdk-8

pipelines:
  default:
    - step:
        name: Build the module
        caches:
          - maven
        script:
          - mvn clean install
        artifacts:
          - omod/target/*.omod
    - step:
        name: Push to the OpenMRS repository
        script:
          # clone and checkout the dev branch
          - git clone --depth 1 $OPENMRS_REPO_URL repo
          - cd repo
          - git checkout dev
          # replace the module in the repository
          - cp ../omod/target/*.omod cfl/web/cfl-modules
          # set up git author
          - git config --global user.email $PIPELINES_GIT_EMAIL
          - git config --global user.name $PIPELINES_GIT_NAME
          # commit the new module
          - git add .
          - git commit -m "Automated SMS module update"
          # push to the repository
          - git push origin dev

