image: maven:3.6.1-jdk-8

pipelines:
  default:
    - step:
        name: Build the module
        caches:
          - maven
        script:
          - mvn clean install
        artifacts:
          - omod/target/*.omod
    - step:
        name: Push to OpenMRS repository
        script:
          - git clone --depth 1 $OPENMRS_REPO_URL repo
          - cd repogit 
          - git checkout dev
          - cp ../omod/target/*.omod cfl/web/cfl-modules
          - git add .
          - git commit -m "Automated SMS module update"
          - git push origin dev

