image: maven:3.6.1-jdk-8

pipelines:
  default:
    - step:
        name: Build the module
        caches:
          - maven
        script:
          - mvn clean install
        artifacts:
          - omod/target/*.omod
